name: linter self test

on:
  push:
    branches-ignore:
      # ignore tmp branches used by bors
      - 'staging.tmp*'
      - 'trying.tmp*'
      - 'staging*.tmp'
      # ignore nolints
      - 'nolints'
      # do not build lean-x.y.z branch used by leanpkg
      - 'lean-3.*'
      # ignore staging branch used by bors, this is handled by bors.yml
      - 'staging'

jobs:
  lint_self_test:
    name: Ensure the linter works
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        python-version:
          - name: 3.8
          - name: 3.9
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version.name }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version.name }}

      - name: sanity check the linter
        run: |
          ./scripts/lint_style_sanity_test.py
